-- 1) テーブル作成
CREATE TABLE categories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  deleted_at timestamptz
);

CREATE TABLE questions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text VARCHAR(255) NOT NULL,
  category INT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  status INT NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  deleted_at timestamptz
);

CREATE TABLE answers (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id INT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  text VARCHAR(255) NOT NULL,
  category INT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  deleted_at timestamptz
);

CREATE TABLE quiz_choices (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id INT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  choice_text VARCHAR(255) NOT NULL,
  is_correct BOOLEAN NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  deleted_at timestamptz
);

CREATE TABLE quiz_results (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id INT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  selected_choice_id INT NOT NULL REFERENCES quiz_choices(id) ON DELETE CASCADE,
  answered_at timestamptz DEFAULT now(),
  session_id VARCHAR(50)
);

CREATE TABLE site_feedbacks (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  user_name VARCHAR(50),
  comment_text TEXT,
  submitted_at timestamptz DEFAULT now()
);

-- 2) 推奨インデックス（FK列）
CREATE INDEX idx_questions_category ON questions (category);
CREATE INDEX idx_answers_quiz_id ON answers (quiz_id);
CREATE INDEX idx_answers_category ON answers (category);
CREATE INDEX idx_quiz_choices_quiz_id ON quiz_choices (quiz_id);
CREATE INDEX idx_quiz_results_quiz_id ON quiz_results (quiz_id);
CREATE INDEX idx_quiz_results_selected_choice_id ON quiz_results (selected_choice_id);

-- 3) updated_at 自動更新トリガー（テーブル作成後に作成）
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at BEFORE UPDATE ON categories
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER set_updated_at BEFORE UPDATE ON questions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER set_updated_at BEFORE UPDATE ON answers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER set_updated_at BEFORE UPDATE ON quiz_choices
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
